---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: develop/Dockerfile

    # The following commands are executed
    # - Migrate Netbox
    # - Create a user (superuser) for Netbox / Django so that you can log in directly to Netbox. More Infos: makesuperuser.py
    # - Start Netbox     
    command: >
      sh -c "python manage.py migrate &&
             python manage.py makesuperuser &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_qrcode:/source/netbox_qrcode
      # For automatic setup of the Django / Netbox SuperUser
      - ../develop/management:/source/netbox_qrcode/management
    tty: true
  worker:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_qrcode:/source/netbox_qrcode
    tty: true
  postgres:
    image: postgres:14
    env_file: dev.env
    volumes:     
      - pgdata_netbox_qrcode:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_netbox_qrcode: